name: Execute Pipeline

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          -path: main
      
      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
    
      # Run grading feedback
      - name: Exercise feedback
        id: ex_feedback
        run: |
          ./grading/ci/pipeline.sh