name: Execute Pipeline

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Run Exercise Feedback Pipeline
        run: |
          chmod +x project/pipeline.sh
          project/pipeline.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: Validate Outputs
        run: |
          echo "Validating outputs..."
          ls -l project/
