# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # install Python 3.11  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Run your tests. You may need to install dependencies first, e.g. pip install, npm install, etc.
      - name: Install dependencies
        run: |
          # Example installation commands (adjust to your project's needs)
          pip install -r requirements.txt 2>/dev/null || true
          npm install || true
          chmod +x ./project/test.sh  # Ensure the test script is executable

      - name: Run tests
        run: |
          # If your tests are too large or require external data, mock or comment them out.
          # Provide an explanation if you must comment them out.
          ./project/test.sh