# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # install Python 3.11  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Install dependencies and run tests
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          chmod +x ./project/test.sh

      - name: Run tests
        run: |
          ./project/test.sh